### ISSUE TITLE
Из каого учебника у Вас задачи, очень сложно искать условие, когда нумерация не совпадает

### ISSUE THREAD

**Issue by YULIYA2001** [Chawotto/java-algorythm#10]
![image](https://github.com/user-attachments/assets/2b83c564-de6e-4715-8db9-63576e231ec0)

**Comment by YULIYA2001** [comment]
![image](https://github.com/user-attachments/assets/a2f59176-403d-488d-bb04-f8d709e8a8ee)

**Comment by Chawotto** [comment]
Что-то я с цифрами попутал..

**Comment by Chawotto** [comment]
Заменил на другую задачу.
