### ISSUE TITLE
Это зачем, там же конструктор строчкой выше все заполнил

### ISSUE THREAD

**Issue by YULIYA2001** [Chawotto/java-algorythm#12]
https://github.com/Chawotto/java-algorythm/blob/bd119248dea73ac925ee6755522af2ee6c7083e3/%D0%A1%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D1%8C%D1%8F_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0/3/src/main/java/org/example/Main.java#L36-L40

**Comment by Chawotto** [comment]
Хороший вопрос. Исправил.
