### ISSUE TITLE
Условие: Покажите, что красно-черные ДБП обладают памятью: например, если вставить в него ключ, меньший всех других ключей , и сразу же удалить наименьший ключ, то может получиться другое дерево.

### ISSUE THREAD

**Issue by YULIYA2001** [Chawotto/java-algorythm#14]
Условие: Покажите, что красно-черные ДБП обладают памятью: например, если вставить в него ключ, меньший всех других ключей , и сразу же удалить наименьший ключ, то может получиться другое дерево.

Запуск программы: Выберите операцию, Вставить ключ... 

Ручное тестирование какого-то кода занимает много времени, хочу увидеть готовый тест: готовое дерево, которое сразу отображается, затем его же отображение с добавленным наименьшим элементом, затем его отображение после удаления наименьшего ключа.

**Comment by Chawotto** [comment]
Добавил тест.

**Comment by YULIYA2001** [comment]
Не совсем подходящий тест. Что до вставки, что после удаления дерево остается одинаковым.

Условие: Покажите, что красно-черные ДБП обладают памятью: например, если вставить в него ключ, меньший всех других ключей , и сразу же удалить наименьший ключ, **_то может получиться другое дерево._**

Для хорошего теста достаточно было просто в конце добавлять и удалять узел со значением 3, а не 4 (тогда исходное дерево и итоговое отличается цветами узлов в левом поддереве).

Это просто к сведению. Задача засчитана.

**Comment by Chawotto** [comment]
Учел ваше замечание.
