### ISSUE TITLE
Откуда взяли формулу?

### ISSUE THREAD

**Issue by YULIYA2001** [Chawotto/java-algorythm#7]
https://github.com/Chawotto/java-algorythm/blob/44ae65bee725ec7a27d7f8986904863ec1b19e0d/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D1%8C%D1%8F_%D0%B1%D0%B8%D0%BD%D0%B0%D1%80%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0/1/src/main/java/org/example/OptimalBST.java#L24

**Comment by Chawotto** [comment]
Совместил несколько простых формул в одну большую, изменил код для лучшей читаемости.

**Comment by YULIYA2001** [comment]
Откуда формула высоты дерева? Просто она неправильная; по Вашей формуле:
log<sub>2</sub>3=1,585  (~h = 2)
log<sub>2</sub>4=2 (~h = 2)

**Comment by YULIYA2001** [comment]
Высота считается верно, но по формуле из стр. 30 ```return (roundedHeight + (nodeCount - 1)) / nodeCount;``` получается, что чем меньше узлов, тем больше сравнений для одной высоты

![image](https://github.com/user-attachments/assets/047bd79e-a358-423e-88e8-09bf3635d025)

**Comment by Chawotto** [comment]
Вы правы, что-то совсем бред какой-то.
Сейчас должно быть верно.
